version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:9.5
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.development
    networks:
      - nest-caching
  
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - nest-caching

  servers:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nest_server
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
      - /app/node_modules
    depends_on:
      - postgres
      - redis

networks:
  nest-caching:
    driver: bridge