version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:9.5
    ports:
      - '5432:5432'
    env_file:
      - .env.development
    networks:
      - nest-caching
  
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - nest-caching

networks:
  nest-caching:
    driver: bridge